config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources 'contacts'
  resources 'about'
  resources 'services'
  resources 'portfolio'
  resources 'blogs'
  resources 'teams'
  resources 'my_services'
  resources 'pricing'
  resources 'projects'
  resources 'terms_of_use'
  resources 'privacy_policy'
  resources 'faq'
  resources 'projects'
  root to: 'home#index'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :blog_image, BlogImageUploader
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/get_in_touch.rb
class GetInTouch < ApplicationRecord
end

app/models/my_service.rb
class MyService < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update]
  def index
    @blogs = Blog.all.limit(8)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new
    @blog.title = params[:title]
    @blog.body = params[:body]
    @blog.blog_image = params[:blog_image]
    if @blog.save
      flash.now[:notice] = "Blog saved."
      render json: { message: flash[:notice], code: 200}
    else
      flash.now[:alert] = "Blog not saved."
      render json: { errors: @record.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end
  def update
    @blog = Blog.find(params[:id])
    @blog.title = params[:title]
    @blog.body = params[:body]
    @blog.blog_image = params[:blog_image]
    if @blog.save
      flash[:notice] = "Blog Updated."
      render json: { message: flash[:notice], code: 200}
    else
      flash[:alert] = "Blog not saved."
      render json: { errors: @record.errors.full_messages }, status: :unprocessable_entity
    end
  end
  
  private

  def show_limit
    
  end

    def blog_params
    params.require(:blog).permit(:title, :body, :blog_image)
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
    @faq = Faq.all
  end
  
  def new
    @faq = Faq.new
  end
  
  def create
    @faq = Faq.new(faq_params)
    if @faq.save
      flash[:message] = "Faq successfully created!"
      redirect_to new_faq_path
    else
      flash[:error] = "Faq not created!"
      render :action => "new"
    end
  end
  
  private
  
  def faq_params
    params.require(:faq).permit(:query, :answer)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blogs = Blog.order(updated_at: :desc).limit(3)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_services_helper.rb
module MyServicesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/pricing_helper.rb
module PricingHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/terms_of_use_helper.rb
module TermsOfUseHelper
end

app/views/faq/index.html.erb
<style>
    .accordion-item {
        background-color: #f8f9fa; /* Set the default background color for closed accordion items */
    }
    .accordion-button {
        background-color: #f8f9fa; /* Set the background color for the accordion button */
    }
    .accordion-button:not(.collapsed) {
        background-color: #e9ecef; /* Set the background color for the accordion button when expanded */
    }
    .accordion-button.collapsed {
        background-color: #f8f9fa !important; /* Set the background color for the accordion button when collapsed */
    }
    .btn-background-accordion{
        background-color: #f8f9fa !important;
    }
</style>
<!-- Hero Start -->
<section class="bg-half-80 d-table bg-primary bg-gradient w-100">
  <div class="bg-overlay bg-gradient-overlay"></div>
  <div class="container">
    <div class="row mt-5 justify-content-center">
      <div class="col-12">
        <div class="title-heading text-center">
          <small class="text-white-50 mb-1 fw-medium text-uppercase mx-auto">Questions & Answers</small>
          <h5 class="heading fw-semibold mb-0 page-heading text-white title-dark">FAQs</h5>
        </div>
      </div><!--end col-->
    </div><!--end row-->

    <div class="position-middle-bottom">
      <nav aria-label="breadcrumb" class="d-block">
        <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
          <li class="breadcrumb-item"><a href="index.html">TouchRails</a></li>
          <li class="breadcrumb-item active" aria-current="page">FAQs</li>
        </ul>
      </nav>
    </div>
  </div><!--end container-->
</section><!--end section-->
<!-- Hero End -->

<section class="section">
  <div class="accordion mt-4 pt-2">
    <div class="container mt-5">
      <% @faq.each_with_index do |faq, index| %>
        <div class="accordion-item mt-5 accordion-item rounded border-0 shadow">
          <h2 class="accordion-header" id="faqItem<%= index + 1 %>">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index + 1 %>">
              <b class="text-dark">Question #<%= index + 1 %>: <%= faq.query %></b>
            </button>
          </h2>
          <div id="collapse<%= index + 1 %>" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
            <div class="accordion-body">
              Answer: <%= faq.answer.html_safe %>.
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!-- Add more FAQ items similarly -->

app/views/faq/new.html.erb
<!-- Hero Start -->
<section class="bg-half-170 d-table w-100" style="background: url('<%= asset_path 'bg/about.jpg' %>') center;">
  <div class="bg-overlay bg-gradient-overlay"></div>
  <div class="container">
    <div class="row mt-5 justify-content-center">
      <div class="col-12">
        <div class="title-heading text-center">
          <!--          <small class="text-white-50 mb-1 fw-medium text-uppercase mx-auto">Get in touch</small>-->
          <h5 class="heading fw-semibold mb-0 page-heading text-white title-dark">Frequently Asked Questions</h5>
        </div>
      </div><!--end col-->
    </div><!--end row-->

    <div class="position-middle-bottom">
      <nav aria-label="breadcrumb" class="d-block">
        <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
          <li class="breadcrumb-item"><a href="index.html">Starty</a></li>
          <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
        </ul>
      </nav>
    </div>
  </div><!--end container-->
</section><!--end section-->
<section class="section container">
  <%= form_with(model: @faq, url: faq_index_path, method: :post, local: true) do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= f.label :query %>
      </div>
      <div class="col-md-12">
        <%= f.text_field :query, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="row mt-4">
      <div class="col-md-12">
        <%= f.label :answer %>
      </div>
      <div class="col-md-12">
        <%= f.text_area :answer, class: 'form-control', rows: 4, required: true %>
      </div>
    </div>
    <div class="row mt-4">
      <div class="col-md-12"></div>
      <div class="col-md-12">
        <%= f.submit 'create', class: 'btn btn-primary form-control' %>
      </div>
    </div>
  <% end %>
</section>